bld/namelist_files/use_cases/sd_waccm_ma_cam6.xml
cime_config/config_component.xml
cime_config/config_compsets.xml
cime_config/testdefs/testlist_cam.xml
test/system/archive_baseline.sh

Tag name: cam_cesm2_1_rel_34
Originator(s): fvitt, dkin
Date: 2 Oct 2019
One-line Summary: Updates for half-degree FWmaSD
Purpose of changes:
Add support for 1.9x2.5 FWmaSD (WACCM middle atmosphere chemistry with
specified dynamics)
Correct "-chem" configure option in CAM_CONFIG_OPTS for FXmad* compsets
-- the 'additive' modifier for CAM_CONFIG_OPTS caused the setting to be
"-chem waccm_ma -chem waccm_mad" for CAM40%WXIED (WACCM-X with
D-region chemistry).  The change here distiguishes "CAM40%WXIE" from
"CAM40%WXIED" so that only waccm_mad is selected for CAM40%WXIED.
Bugs fixed (include bugzilla ID):
Describe any changes made to build system:
Describe any changes made to the namelist:
List any changes to the defaults for the boundary datasets:
Describe any substantial timing or memory …

twodeg_cam_cesm2_1_rel

---

Externals.cfg

SInce it appears that there are no more tags coming before the release, I am bringing this change of ww3 coming from git instead of svn in by itself.

cam_cesm2_1_rel_37: Bring in ww3 external from git

---

Externals.cfg

cam_cesm2_1_rel_39: update CIME external to bring in tag with fix for RCE

---

cime_config/testdefs/testlist_cam.xml
cime_config/testdefs/testmods_dirs/cam/outfrq9s_wcm_ne30/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_wcm_ne30/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq9s_wcm_ne30/user_nl_clm
src/physics/waccm/efield.F90

A proposed workaround for an issue with intel/19.0.2 on cheyenne
New tests added :
aux_cam:
ERP_Ln9.ne30pg3_ne30pg3_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30
prealpha:
SMS_Ln9.ne30_ne30_mg17.FW2000climo.cheyenne_intel.cam-outfrq9s_wcm_ne30
fixes #68

cam6_2_013: Changes to efield module to workaround an issue with intel 19

---

bld/build-namelist
src/physics/cam/micro_mg3_0.F90
src/physics/cam/micro_mg_utils.F90
src/physics/cam/physics_types.F90
test/system/archive_baseline.sh

Fixes bug introduced in #46 where empty_htapes is always set to false
Bring in Andrew Gettelman's MG3 misc changes
Remove unused variables in physics_types.F90
Change location for storage of CAM baseline tests to AMWG space on cheyenne
#72 and #75 were reviewed independently and #64 does not require review.  Hence there is no review requested for this tag (unless anyone decides to do so anyway)
Closes #64 
Closes #72 
Closes #75

cam6_2_014: Empty htapes bug fix and misc changes

---

src/physics/cam/micro_mg3_0.F90
src/physics/cam/micro_mg_utils.F90

This changes 2 files; comments in micro_mg_utils.F90.
In micro_mg3_0.F90, the code will tolerate both do_graupel and do_hail = true (CAM at higher levels does not allow it, but the microphysics does permit it).  The changes move the places where  do_graupel and do_hail appear separately so that graupel is always last. This will give an equivalent result to do_graupel = true, do_hail = false when both are true.
It also needs to propagate to the PUMAS repository for the microphysics (@Katetc ) can handle that hopefully....
Fixes #74

part of cam6_2_014: mg utils comment change, mg3 graupel order change

---

bld/build-namelist

All namelists were having empty_htapes be set to false (accidentally introduced in cam_snapshot tag). #46 
Tested this fix with and without cam_snapshot setting and resulting atm_in file has appropriate settings.

part of cam6_2_014: Fix bug where empty_htapes was always set to false 

---

Externals.cfg
src/cpl/nuopc/atm_comp_nuopc.F90
src/physics/rrtmg/radiation.F90
src/physics/rrtmg/rrtmg_state.F90

- **Fix deallocation bug in RRTMG**: Remove pointer property from  `r_state` so that it is no longer allocated or deallocated.
- **Modify NUOPC cap to set orbital values**: Set orbital parameters directly in CAM NUOPC cap
- **Remove unused WW3 external**
fixes #86 
fixes #88 
fixes #89 
All regression tests pass on Cheyenne and Izumi.
RRTMG fix already reviewd by @brian-eaton, @cacraigucar, and @nusbaume.
NUOPC modification reviewed by @gold2718

Miscellaneous fixes

---

src/physics/rrtmg/radiation.F90
src/physics/rrtmg/rrtmg_state.F90

modified:   doc/ChangeLog
modified:   src/physics/rrtmg/radiation.F90
modified:   src/physics/rrtmg/rrtmg_state.F90
I ran 2 cases (f19 and f09 resolutions) for 10 days successfully on cheyenne, both with DEBUG=TRUE and NTHRDS=3.
Fixes issue #86

part of cam6_2_016: Workaround rrtmg_state pointer issue on cheyenne

---

CODE_OF_CONDUCT.md

This updates the CAM code of conduct (COC) to the UCAR model version. 
https://doi.org/10.5065/6w2c-a132
I'm not sure if this should just go to this branch or other branches as well. I'm assuming you can bring this in and then push it to other branches that might need it.
The above COC needs to be used on projects with a strong UCAR/NCAR involvement/management. This is also important to have because of NSF funding requirements.
There are a few things added to the list of behaviors. But, it also maps out possible consequences for bad behavior. Even people not working for UCAR can involve UCAR resources to resolve issues.
It would be good for the CAM community to review the list and confirm everyone is onboard with it.

Update to the new UCAR contributor code of conduct

---

Externals.cfg
bld/configure

The external for cice was already further along, so did not move it backwards.
Using the latest cime tag (one beyond what was used in cesm2_2_beta04) as it was tested and helped the problem that some of the scientists have been experiencing 
Note-- configure needed to be slightly modified to support CAM standalone testing as the MCT locations changed for the slab models in the updated cime
Closes #116

cam6_2_022: Update externals to at least match cesm2_2_beta04

---

src/chemistry/modal_aero/modal_aero_rename.F90

Remove open file statements which are not needed 
Remove commented out debugging code
Closes issue #131
I have confirmed that the modal_aero_rename_no_acc_crs_sub routine has been exercised in our regression tests.  I don't know why this has not been a problem before.

cam6_2_024: Remove open file statements in MAM exchange code

---

.github/scripts/branch_pr_issue_closer.py
.github/workflows/branch_push_workflow.yml
test/system/TGIT.sh

Closes #82 
This script will allow for issues and pull requests to be closed when specified using the github keywords in the text of a merged pull request to the non-default cam_development branch (and any future branches which are created from cam_development).  If an issue is associated with more than one project, then this script will instead move the relevant project card to the "closed issues" column, and will only officially close the issue once the card has been moved for all relevant projects. 
This script requires that any new project must have the exact same column names and organization (including automation settings) as the "CAM Development branch" project.  This is because current limitations in the Github API require that column names must be hard-coded, although in the …

Add issue-closing python script for github action

---

.github/scripts/branch_pr_issue_closer.py

I forgot that there are some project cards that are neither issues nor PRs, which caused the script to fail (I believe these were brought over when we first transitioned to github).
This quick fix allows the script to keep running even when it runs into those kind of cards.
closes #82

Hotfix for issue closing script

---

bld/namelist_files/namelist_definition.xml
src/control/scamMod.F90
src/dynamics/eul/iop.F90
src/physics/cam/physpkg.F90

The PR takes closes issue #130 where there were erroneous default values in the namelist definition file.  I also included some minor cleanup to the scam iop variables as well as corrected a bug for the upcoming SAS IOP file.

cam6_2_025?: Mods to resolve issue #130 SCAM6 namelist definitions inconsistent

---

.github/scripts/branch_pr_issue_closer.py
.github/workflows/branch_push_workflow.yml

This PR was created to add conditionals to the Github action workflow for push events so that the issue-closing script only triggers when the push is to the main ESCOMP/CAM repo, and not to anyone's fork.
Fixes #136

Prevent Github action from running on forks

---

Externals_CAM.cfg
bld/namelist_files/namelist_definition.xml
cime_config/testdefs/testlist_cam.xml
cime_config/testdefs/testmods_dirs/cam/outfrq9s_ocnemis/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_ocnemis/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq9s_ocnemis/user_nl_clm
src/chemistry/mozart/chemistry.F90
src/chemistry/mozart/ocean_emis.F90

Provide the capability to exchange chemical tracers between atmosphere and ocean.  The introduced ocean_emis module provides surface sources and sinks of atmospheric chemical tracers which uses prescribed ocean conditions inputs.
A new chemistry preprocessor is included in the externals.  This can handle larger chemical mechanisms that have 1000 or more reactions.
closes #115 
closes #114

cam6_2_027: Air-sea exchange module for chemical tracers

---

Externals.cfg
test/system/CAM_compare.sh
test/system/test_driver.sh

cime and test_driver.sh need to be updated to handle new izumi compilers
Fixes #145 
Note that the EQ tests are failing   The summary is:
SUMMARY of cprnc:
 A total number of    297 fields were compared
          of which      0 had non-zero differences
               and      0 had differences in fill patterns
               and      0 had different dimension sizes
 A total number of      2 fields could not be analyzed
 A total number of      5 time-varying fields on file 1 were not found on file 2.
 A total number of      0 time-constant fields on file 1 were not found on file 2.
 A total number of      0 time-varying fields on file 2 were not found on file 1.
 A total number of      0 time-constant fields on file 2 were not found on file 1.
  diff_test: the two files DIFFER only in …

cam6_2_029: Updates for using latest izumi compilers

---

src/physics/cam/gw_common.F90

fixes #147
Note: This fix is a workaround, the underlying source of the cascading error caused by small values still should be tracked down and fixed.

cam6_2_030: Fix for floating point issue in GW drag.

---

Externals_CAM.cfg
bld/namelist_files/use_cases/waccmx_ma_2000_cam6.xml
bld/namelist_files/use_cases/waccmx_ma_hist_cam6.xml
cime_config/config_component.xml
cime_config/config_compsets.xml
cime_config/testdefs/testlist_cam.xml
cime_config/testdefs/testmods_dirs/cam/waccmx_weimer/user_nl_cam

For CESM2.2 have these WACCMX compsets
FX2000               : 2000_CAM60%WXIE_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
FXHIST               : HIST_CAM60%WXIE_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
FXmadHIST            : HIST_CAM60%WXIED_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
FXSD                 : HIST_CAM60%WXIE%SDYN_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
FXmadSD              : HIST_CAM60%WXIED%SDYN_CLM50%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
closes #125 
Update external atmos_phys to version0_00_005 
fixes #142

cam6_2_032: WACCMX compsets for CESM2.2

---

bld/namelist_files/namelist_defaults_cam.xml

modified:   bld/namelist_files/namelist_defaults_cam.xml
closes #161

cam6_2_035: add default historical emissions for ne30pg2 and ne30pg3 grids

---

Externals.cfg

This update is to bring in the answer changes for CTSM dev 105 in a non-code changing tag.  Note that FXHIST will be broken until dev106 is brought in.
Closes #173

cam6_2_038: Use cesm2 2 alph06c externals

---

Externals.cfg
src/chemistry/utils/input_data_utils.F90

modified:   Externals.cfg
modified:   src/chemistry/utils/input_data_utils.F90
fixes #182 
fixes #175 
NOTE: The majority of aux_cam baseline tests fail due to changes in clm IC file.

cam6_2_042: Update clm external to ctsm1.0.dev107; fix input data issue #175

---

cime_config/config_pes.xml
cime_config/testdefs/testlist_cam.xml
cime_config/testdefs/testmods_dirs/cam/outfrq1d_refined_camchem/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_mg3/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_refined_camchem/shell_commands

Hi all,
There are several small, non-code changes in this PR - it's my first, so bear with me, and provide any and all feedback that might help in the future:
1) Switched the ne30 QSC6 prebeta test to QPC6:
Fixed #195 
2a) Removed Yellowstone/Casper entries from config_pes.xml
2b) Removed Edison/Eos entries (decommissioned systems) from config_pes.xml
Fixed #185 
3a) Added entries for FV3 grids:
C24 - 1 node, ~9.1 SYPD
C48 - 4 nodes, ~9.7 SYPD
C96 - 16 nodes, ~8.5 SYPD
C192 - 32 nodes, ~2.9 SYPD
C384 - 32 nodes, ??? SYPD
These last two had slowdown during initialization due to non-scalable sections of code, so further tests were not yet done.  We can retest and alter these with new code that addresses those.
3b) Added entries for SE RR grids:
ne0np4.ARCTIC.ne30x4 - 91 nodes, ??? SYPD …

cam6_2_045: Cleanup on config_pes.xml and change to testlist_cam.xml

---

.github/workflows/branch_push_workflow.yml

Removes the branch check from the workflow, so that the action will run regardless of which branch the code changes are being pushed to.
Fixes #209

Modify Github Action push workflow so that it runs on all future branches.

---

.github/workflows/branch_push_workflow.yml

Removes the branch check from the workflow, so that the action will run on pushes to the CESM2.2 release branch.
Fixes #209

Modify Github Action push workflow so that it runs properly on CESM2.2 release branch

---

.github/scripts/branch_pr_issue_closer.py

Fix bug in issue-closing script so that creating a tag with the same commit message as the original PR merge commit doesn't result in a failure.  Also improve the error message when a non-existent issue number is referenced.
Fixes #242
Tests were run on a Github test repo to ensure that the action runs correctly when multiple pushes occur with the same commit message and PR reference (similar to what a tag commit would do).

Fix bug in issue-closing script

---

bld/namelist_files/namelist_definition.xml
src/physics/cosp2/optics/cosp_optics.F90

Fixes #262 
Fixes #265 
This PR also changes answers for COSP, so I am having two scientists double-check the code change.

cam_cesm2_1_rel_52: Fix COSP snow optics bug, and nhtfrq namelist definition.

---

bld/build-namelist
cime_config/testdefs/testlist_cam.xml

Do not set use_hetfrz_classnuc if chemistry does not include MAM species.
Added aux_cam test which uses aquaplanet cam6 physics and -chem none.
closes #261

cam6_3_005: Enable "-chem none" configure option with cam6 physics

---

src/chemistry/mozart/mo_drydep.F90
src/control/cam_history.F90
src/control/cam_restart.F90
src/control/ncdio_atm.F90
src/dynamics/fv/dyn_grid.F90
src/dynamics/se/dyn_comp.F90
src/physics/cam/nudging.F90
src/utils/cam_pio_utils.F90

Fixes to allow CAM to operate with PIO2
Unread buffer locations properly initialized after read for SE dycore.
Fixes to nudging code to work with new weak-scaling infrastructure
Fixes #237 
Fixes #248 
Fixes #263 
Fixes #282 
Closes #241 
Closes #247

cam6_3_008: Fixes for PIO2 plus nudging I/O update

---

bld/configure
bld/namelist_files/namelist_defaults_cam.xml

CAM's bld/configure routine needs to be updated for MPAS to allow it to build under CAM or CESM checkouts.  The namelist defaults also need to be updated to get a MPAS CESM regression test to pass. Fixes #337

cam6_3_011: MPAS doesn't build under CESM checkout.

---

src/cpl/nuopc/atm_comp_nuopc.F90
src/physics/cam/physics_types.F90

This is a port for CMEPS threading in CAM.  The change in physics_types.F90 is due to a stack size issue in the call to flush.  It could also be solved via an OMP master region, but I think that that call in the code is really old and crusty and no longer required.  
Fixes issue #349

part of cam6_3_016: support for nuopc threading

---

bld/namelist_files/use_cases/ssp370BB_smyle_cam6.xml
cime_config/config_component.xml

Adding the smyle compset for the SMYLE project.  Fixes #256

cam_cesm2_1_rel_54: adding smyle branch

---

test/system/test_driver.sh

TR8 and TGIT tests always report "PASS" as they were reporting on the tee command.  Use PIPESTATUS return code instead.
Tested by removing "_r8" on a random variable.  The resulting overall status said FAIL.  Did not test the TGIT logic as it had the exact same structure as the R8.
Closes #341

part of cam6_3_017: Fix TR8 and TGIT return code checks

---

src/chemistry/mozart/mo_usrrxt.F90
src/control/cam_snapshot.F90

This is a fix for the index issue for setting the MPAN+M reaction rate constant
fixes #364
Answer changing only for some CAM-Chem and WACCM compsets

cam6_3_019:  correction to indexing in mo_usrrxt

---

src/control/cam_snapshot.F90

part of cam6_3_019: Remove duplicate pbuf_ in snapshot names

---

Externals_CAM.cfg
bld/configure
src/dynamics/mpas/Makefile

New MPAS external hash to fix MPAS base/rest regression failure introduced in cam6_3_020.  Updated MPAS build routines to allow MPAS dycore library to link with the CESM ESMF library.  This change completes NUOPC compatibility for MPAS.
closes #389

cam6_3_023: fix for mpas regression failure (issue #389) and MPAS makefile update for NUOPC

---

cime_config/buildcpp
cime_config/buildlib
cime_config/buildnml

Updates python in buildcpp, buildlib and buildnml
Closes #394

cam6_3_025: Use python3 for cime_config scripts

---

Externals_CAM.cfg
bld/build-namelist
bld/namelist_files/namelist_defaults_cam.xml
bld/namelist_files/namelist_definition.xml
src/dynamics/mpas/Makefile
src/dynamics/mpas/driver/cam_mpas_subdriver.F90
src/dynamics/mpas/dyn_comp.F90

Update the MPAS-A dycore in CAM to a stable hash on the MPAS-Model's 'develop' branch.
With the update to a newer MPAS-A dycore, several changes are needed in CAM-MPAS:
1. New MPAS-A namelist options need to be handled in CAM-MPAS
2. The dycore Makefile needs to correctly account for new dependencies in the dycore
3. Additional calls to MPAS-A init/finalize routines need to be made at appropriate points in CAM-MPAS
4. Acquisition of pointers to certain dycore fields need to be moved to account for new memory allocation strategies in the updated dycore
This PR closes #417.

cam6_3_030: Update the MPAS-A dycore to MPAS-Atmosphere v7+

---

Externals.cfg
test/system/test_driver.sh

Update Externals.cfg to match CESM 2.3 alpha 05c
Addresses #423 
Testing is a bit tricky since the test names are different in the new CIME. To allow checks to pass, I created a set of dummy baseline directories that is mostly a renamed version of the cam6_3_030 baselines:
- Test directories have the new name (with `_Vmct` added at the end of the test type field)
- Files inside the top level of the test directory are soft links to the cam6_3_030 baseline files (saves disk space)
- Files inside CaseDocs are copies of the cam6_3_030 baseline files _except_:
- esp_modelio.nml: new value for `pio_netcdf_format`
- drv_in: new `case_name` that includes driver type
Because of the updated component externals, there are numerous namelist changes (GLC, CLM, and driver) and a few baseline changes (I …

cam6_3_031: Update externals to cesm2_3_alpha05c

---

Externals.cfg

In preparation for updating CTSM to include a fix for the cam_dev PR #387, update externals so answer changes are isolated to this tag.  CTSM will be brought up to the most recent tag (dev064).

Update cesm2_3_alpha07b externals

---

src/chemistry/mozart/mo_drydep.F90

This removes a large chunk of memory allocation that is not used.
Closes #485

part of cam6_3_041: removed unused memory allocation

---

src/dynamics/se/dyn_comp.F90
src/dynamics/se/dyn_grid.F90

Make ini_grid_hdim_name in dyn_grid public and use in dyn_comp so that GLL grids can use initial data files with ncol_d.
Closes #339

cam6_3_043: Read ncdata file with either ncol or ncol_d dimension (SE dycore)

---

Externals.cfg
bld/build-namelist
cime_config/config_pes.xml
src/dynamics/se/dyn_grid.F90
src/utils/cam_grid_support.F90

Update externals to match those in cesm2_3_beta07  - The only exception is FMS which is newer than the version in CESM
bug fix for SE WACCM-X bug
From @gold2718 regarding WACCM-X bug:
- In the old days (pre physgrid),  the SE dycore always used the 'ncol' dimension.
- With physgrid, data on the GLL grid used 'ncol_d' and data on the physgrid used 'ncol'.
- When the switch was made to always read initial data on the GLL grid, that broke the logic in dyn_grid so Brian put in a fix (in late 2020).
- However, that fix prevented reading initial data on a physgrid run with the 'wrong' dimension name for the GLL data.
- cam6_3_043 included a fix for that problem, however, due to the change made in 2020, that caused the SE dycore to always write out new initial data files using the same dimension …

cam6_3_044: match cesm2_3_beta07 externals and bug fix for SE WACCM-X

---

src/chemistry/mozart/mo_chm_diags.F90
src/chemistry/mozart/mo_gas_phase_chemdr.F90

These changes remove the double call of outfld for HNO3_GAS. In addition, right parantheses were added to some chenistry output field long names, that were missing.
Please note that the changes have not been tested yet.
Closes #517 
@fvitt

Bugfix double call of outfld HNO3_GAS

---

bld/namelist_files/use_cases/ssp370BBext_cam6.xml
cime_config/config_component.xml

LE2-2100extension:  This compset cycles most CAM forcing over year 2100. GHG evolves to 2500. Solar forcing has been extended by MikeMills from 2300 to 2500.  co2flux_fuel_file and aircraft_co2_file files were extended by KLindsay.

part of cam_cesm2_1_rel55:  adding compset for CAM extending 2100-2500 for LE2

---

src/dynamics/se/restart_dynamics.F90

This reduces the memory footprint of the read_elem routine that reads SE dynamics fields from restart files.
Fixes #472

cam6_3_052: Reduce memory footprint of SE dycore read restart

---

cime_config/testdefs/testlist_cam.xml

Changes the compiler from PGI to GNU for the following tests:
- all aux_cam pgi tests
- waccmx pgi test on izumi
- fv3_cam pgi test on izumi
- prebeta pgi test on cheyenne
- aux_cam suite run with gnu compiler and compared against pgi baselines
closes #539

cam6_3_053: Transition izumi PGI tests to GNU compiler

---

cime_config/config_pes.xml
cime_config/testdefs/testlist_cam.xml
cime_config/testdefs/testmods_dirs/cam/waccmx_weimer/shell_commands
src/ionosphere/waccmx/edyn_init.F90

Fixes issue #624 
The follow test passes with these changes:
SMS_D_Ln3_Vnuopc.ne5pg3_ne5pg3_mg37.QPX2000.izumi_nag.cam-outfrq3s
This PR moves this WACCMX test back to izumi_nag

part of cam6_3_071: Corrections to WACCMX coordinate maps for oplus and geomag history grids

---

src/physics/camrt/radiation.F90
src/physics/rrtmg/radiation.F90

Closes #655 
This fixes a bug where restarts were changing answers on some timesteps.
Compared with previous tags:
BFB for regular runs
Answer changing for restart runs when radiation was run on the restart time step.
Note this was reviewed in #659 when was going to be combined with a couple of other PRs

cam6_3_078: Making nextsw_cday a double type to fix cam_dev restart bug.

---

src/control/cam_history.F90
src/dynamics/se/dycore/interpolate_mod.F90
src/dynamics/se/interp_mod.F90

This Pull Request contains a few bug fixes for the `interpolate_output` option for the SE dycore.  Specifically, it allows for single-precision (e.g. `ndens = 2`) interpolated output, and allows for variables with missing values (e.g. `AODVIS`) to be output correctly in the standard monthly average (`h0`) files, at least for certain SE-CSLAM grids. 
Please note however that variables with missing values may still have "bad" values at the missing value margins when either using very high resolution grids or outputting at high frequencies (e.g. every hour or every time step).  To fix this issue completely will potentially require a much larger set of code modifications, which might be beneficial to do in conjunction with future developments (e.g. the creation of a dycore-agnostic …

Bug fixes for interpolate_output routines

---

src/cpl/nuopc/atm_comp_nuopc.F90

This fixes #670 - but also needs an accompanying CMEPS PR https://github.com/ESCOMP/CMEPS/pull/314.
To have the DAE test pass, the CMEPS must point to cmeps0.13.74 or later. However, this PR can be merged without a  CMEPS PR as long as the DAE test is not expected to pass.

fixes for dae test

---

src/control/cam_history_support.F90

Hello,
This updates `cam_history_support`'s `fieldname_len` parameter from `24` to `32`, in order to accommodate longer names for history outputs. This is in support of implementing GEOS-Chem (https://github.com/ESCOMP/CAM/pull/484) into CESM, as we recently implemented a feature to automatically pass GEOS-Chem diagnostic quantities to CAM history. Some of the GEOS-Chem field names are longer than 24 characters and thus we need to increase the maximum length.
The model was verified to run correctly with this change so I'm making a pull request. It would be helpful to discuss here as well if the 24-character limitation was imposed due to impacts on other components, or it is artificial and can be expanded as required.
Thank you!
Haipeng Lin

part of cam6_3_084 : Update maximum CAM history field length to 32 (up from 24).

---

Externals.cfg

Externals updated to match the cesm2_3_alpha10b tag:
- ccs_config_cesm0.0.47
- cmeps0.13.78
- share1.0.13
- cime6.0.64
- ctsm5.1.dev107
Externals with a more recent tag than cesm2_3_alpha10b tag (to fix PE layout issue):
- cesm_cice6_2_0_35
- cdeps0.12.67
closes #661 
closes #673 
addresses #670

cam6_3_085: Update externals to match cesm2_3_alpha10b

---

bld/configure
cime_config/buildcpp
cime_config/buildlib

Changes found in the port to gust.   python paths to cime needed to be updated.  ali_arms has an issue with the nvhpc compiler but is only needed by waccm and so most builds can avoid this issue.   oneapi compiler needed to be added. 
(oneapi is the ncar name for the llvm based version of the intel compiler) Finally MODEL has been depricated in the call to make and replaced by COMP_NAME.
Closes #705

update python paths, only build ali_arms with waccm

---

src/cpl/nuopc/atm_comp_nuopc.F90

Although orbital parameters were not being printed on every timestep as reported in #704 they were still being printed more than once, this should address that issue.

reduce the number of times orb_param is printed to log

---

.github/workflows/branch_push_workflow.yml

Last one!  This is for the CESM2.1 release branch.
Fixes #718
Also updates the Github checkout versions to avoid future deprecation problems.

Update issue closing workflow in order to avoid Github Action failures.

---

src/physics/spcam/ecpp/module_ecpp_ppdriver2.F90

Closes #717
Note that this was just turned off like all of the other optional writing commands in ECPP with a -1.
This code mod was tested before and after making the change using ` ./create_test ERS_Ln9_Vnuopc.f19_f19_mg17.FSPCAMM.izumi_gnu.cam-outfrq9s` and the fort.155 file was not written out once the change was made.

part of cam6_3_087: Turn off unit 155 ECPP writing by default

---

Externals.cfg
cime_config/testdefs/testmods_dirs/cam/carma_sea_salt/shell_commands
cime_config/testdefs/testmods_dirs/cam/dartcambigens/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq3s_chemproc/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_apmee/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_mee_fluxes/shell_commands

Match externals for cesm2_3_alpha11a, except for the externals which CAM has newer and the FMS external which is older
Closes #730

cam6_3_088:  Update externals to match cesm2_3_alpha11a - more or less

---

src/dynamics/se/dycore/prim_advance_mod.F90

Same fix as #685 
TT_UN noise indeed disappears at ~270hPa:
Answers at ~3hPa seem more different than in cam_development:
closes #678

cam_cesm2_2_rel_05: Secondary advection bug cesm2 2

---

cime_config/testdefs/testmods_dirs/cam/outfrq1d_14dec_ghg_cam_dev/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq1d_physgrid_tem_mpasa120_wcmsc/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq3s_physgrid_tem/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq9s_physgrid_tem_1deg/user_nl_cam
src/physics/cam/phys_grid_ctem.F90
src/physics/cam_dev/physpkg.F90

fixes #769 
Also :
- adopts the `zm` naming convention for the zonal mean outputs.  
- add 'Uzm','Vzm','Wzm','THzm' output fields

cam6_3_102: Fix cam_dev TEM diags issue

---

Externals.cfg

Update externals to match cesm2_3_alpha12d with the following exceptions:
- CLM tag is one newer than was used in alpha12d as it contains some of the coarse grid modifications
- FMS is an older version (inherited from cam6_3_102)
- cpl7 is one tag newer (inherited from cam6_3_102)
Closes #733

Update externals to almost match cesm2_3_alpha12d

---

Externals.cfg
bld/build-namelist
bld/namelist_files/namelist_definition.xml
src/chemistry/mozart/chemistry.F90
src/chemistry/mozart/mo_chemini.F90
src/chemistry/mozart/mo_lightning.F90
src/chemistry/mozart/ocean_emis.F90
src/control/camsrfexch.F90
src/control/runtime_opts.F90
src/cpl/nuopc/atm_import_export.F90
src/physics/cam/physpkg.F90
src/physics/cam_dev/physpkg.F90

Fix issue with ocean emissions in B compsets where SSTs are zero over land.
fixes #794 
closes #567
closes #747

cam6_3_108: Ocean emissions fix

---

bld/namelist_files/namelist_definition.xml
cime_config/config_compsets.xml
src/control/cam_history.F90
src/physics/cam/cam_diagnostics.F90
src/physics/cam/clubb_intr.F90
test/system/archive_baseline.sh

Resolve issues:
. Issue #371 - Grid matches in refcases will need to change from gland4 to gris4 if they are re-enabled
- Resolved by removing entries for old refcases.
. Issue #741 - Updates to address CLUBB variable-name length limit.
- Use cam_history_support::max_fieldname_len to replace hardcoded 16.
- PR #743 will be resolved by this PR.
. Issue #608 - Fix path for buildlib/buildnml
- Fix one wrong occurance of the old path 'cime/scripts/Tools'.  Don't see any problem with paths for buildlib/buildnml.
. Issue #749 - Correct description of low-level wind output
- fix description as suggested
. resolves #371
. resolves #741
. resolves #743
. resolves #608
. resolves #749
. resolves #803

cam6_3_110: Resolve miscellaneous issues.

---

bld/build-namelist
bld/namelist_files/namelist_defaults_cam.xml
bld/namelist_files/use_cases/1850_cam_lt.xml
bld/namelist_files/use_cases/1850_cam_mt.xml
bld/namelist_files/use_cases/hist_cam_lt.xml
bld/namelist_files/use_cases/hist_cam_mt.xml
cime_config/config_component.xml
cime_config/config_compsets.xml

cam6_3_111: create CAM LT and MT 1850 use_cases

---

bld/namelist_files/use_cases/ssp585BB_cam6.xml
cime_config/config_component.xml

cam_cesm2_1_rel_r58: Use case to support BSSP585smbb compset.

---

Externals.cfg
bld/namelist_files/namelist_defaults_cam.xml
cime_config/testdefs/testlist_cam.xml

Add support for running SE ne3pg3 out of the box.  Mostly used for testing.

cam6_3_115: Add support for additional SE grids

---

src/control/cam_history.F90
src/dynamics/se/dycore/fvm_consistent_se_cslam.F90

This pull request is a fix for derecho performance as discussed in https://github.com/ESCOMP/CAM/discussions/827 
Testing was performed by creating a baseline using SMS_Ln9.ne30pg3_ne30pg3_mg17.FLTHIST_v0c.derecho_intel.cam-outfrq9s
and comparing unmodified fvm_consistent_se_cslam.F90 to the modified version.
Results were bfb.   A 20day PFS test with the same compset shows a speed up from 5.5 ypd to 17.4 ypd.
A PFS test was also conducted with the nvhpc/23.1 compiler, no notable change in performance.

add pointers for intel performance, remove unused PI variable for nvhpc

---

src/control/cam_history.F90

Fixes issue #876 Significantly improves cam history write time.
Testing - 
I ran test PFS_P2160.ne30pg3_ne30pg3_mg17.FLTHIST_v0d.derecho_intel with 
user_nl_cam
`! Users should add all user specific namelist changes below in the form of 
! namelist_var = new_namelist_value 
mfilt=1,1,1,1,1,1
ndens=1,1,1,1,1,1
nhtfrq=-6,-6,-6,-6,-6,-6
`
And Environment variable:
`
MPICH_MPIIO_HINTS=*.nc:romio_cb_read=enable:romio_cb_write=enable:striping_factor=48:striping_unit=4194304
`
This resulted in:
Model Cost:            5659.69   pe-hrs/simulated_year 
Model Throughput:         9.23   simulated_years/day 
cam_run4_wrapup                                               2160   2160   961      70.6861     70.6560     384     70.8260     1885 
Using the original cam_history.F90:
Model Cost: …

improves history write performance;

---

bld/namelist_files/namelist_defaults_cam.xml

This PR modifies the namelist_defaults.xml to add 2 new ncdata files for compsets using 60 and 30km MPAS-A resolutions and analytic initial conditions.
Closes #847

cam6_3_126: Add MPAS-A 60 and 30km ncdata and related changes

---

Externals.cfg
Externals_CAM.cfg
cime_config/buildlib
test/system/test_driver.sh

Closes #879 (test_driver.sh supports derecho)
Closes #886 (fix line too long in HEMCO external)
Updates externals to match cesm2_3_alpha16d (except ccs_config is newer)
Limited review as reviews were performed in #884 before it was broken into a more limited PR

cam6_3_129:  Update externals to match cesm2_3_alpha16d and bring in test_driver which supports derecho

---

test/system/test_driver.sh

I added support for running tests on derecho.  I set up the derecho tests to use the cheyenne test lists.  Once the transition to derecho is finished we can rename the cheyenne tests to derecho, and update test_driver.sh
I noticed that CAM_RESTART_TASKS and CAM_RESTART_THREADS aren't being used on cheyenne or derecho.  But I didn't want to remove them in case they are used.  There's still issues with with the PE layouts on derecho so several of the tests are failing.
Addresses: #875 
Here's a list of the aux_cam tests that were failing for me.
`FAIL ERP_Ld3_Vnuopc.f09_f09_mg17.FWHIST.derecho_intel.cam-reduced_hist1d RUN time=2423
FAIL ERP_Lh12_Vnuopc.f19_f19_mg17.FW4madSD.derecho_intel.cam-outfrq3h COMPARE_base_rest
FAIL ERP_Ln9_P24x3_Vnuopc.f45_f45_mg37.QPWmaC6.derecho_intel.cam-outfrq9s_ …

part of cam6_3_129: Add derecho support to test_driver.

---

bld/namelist_files/namelist_definition.xml
src/dynamics/fv/dp_coupling.F90
test/system/archive_baseline.sh

This PR corrects a bug introduced in cam6_3_109.  Physics requires constituents mixing ratios to be dry but was using constituent thermodynamic properties based on the wet mixing ratio returned by dynamics.  To fix this bug, the routine called to convert mixing ratios from wet to dry was moved further up in d_p_coupling so that it is called before the thermodynamic properties are calculated for physics. 
An additional fix to close issue #690 was added to correct namelist default types which are used to control the effect of the SE sponge layer. se_sponge_del4_nu_div_fac has been redefined from and integer to a real type as it controls real valued coefficient.  se_sponge_del4_lev was defined as a real but identifies a specific integer model level and has been redefined from a real to …

WACCMX-FV bug fix:convert wet species to dry before calling cam_thermo_dry_air_update

---

bld/namelist_files/namelist_defaults_cam.xml
bld/namelist_files/namelist_definition.xml
cime_config/config_pes.xml
cime_config/testdefs/testlist_cam.xml
src/control/cam_history.F90
src/dynamics/se/dycore/global_norms_mod.F90
src/dynamics/se/dycore/prim_advance_mod.F90
src/ionosphere/waccmx/edyn_init.F90
src/ionosphere/waccmx/edynamo.F90
src/ionosphere/waccmx/ionosphere_interface.F90
src/physics/cam/vertical_diffusion.F90

Introduce a hybrid PGF option in the SE dycore for WACCM-x to make WACCM-x consistent with PGF used in CAM in the troposphere and traditional PGF formulation above to solve stability issues with the SE dycore (fixes #896)
Set reasonable default PE layouts for WACCM(x) and CAMChem on derecho. This solves some of the regression test failures listed in #892
Implements PHIHM history field for waccmx -- High Latitude Electric Potential
Fixes #681

cam6_3_133: Hybrid PGF option in the SE dycore for WACCM-x and other misc updates

---

Externals_CAM.cfg
bld/configure
src/dynamics/se/dp_coupling.F90
src/dynamics/se/dycore/dyn_time_mod.F90
src/dynamics/se/dycore/fvm_consistent_se_cslam.F90
src/dynamics/se/dycore/prim_advance_mod.F90
src/dynamics/se/dycore/prim_advection_mod.F90
src/dynamics/se/dycore/prim_driver_mod.F90
src/dynamics/se/dycore/prim_init.F90
src/dynamics/se/dycore/prim_state_mod.F90
src/dynamics/se/dycore/se_dyn_time_mod.F90
src/dynamics/se/dyn_comp.F90
src/dynamics/se/dyn_grid.F90
src/dynamics/se/restart_dynamics.F90
src/dynamics/se/stepon.F90
src/physics/cam/geopotential.F90
src/physics/cam/physpkg.F90
src/physics/cam/ref_pres.F90
src/physics/cam_dev/physpkg.F90
src/physics/simple/held_suarez_cam.F90
src/physics/simple/kessler_cam.F90
src/physics/simple/physpkg.F90
src/utils/cam_ccpp/ccpp_constituent_prop_mod.F90
src/utils/cam_ccpp/ccpp_kinds.F90
src/utils/ccpp_constituent_prop_mod.F90

This PR updates the atmospheric_physics external in CAM, which requires some source modifications on the CAM-side.  There has also been some replacement of CAM code with CCPP physics routines in order to reduce duplication.
Finally, this PR also fixes a bug found in Kessler where it was using the wrong pressure when converting to/from potential temperature via the exner function.
Fixes #752 
Fixes #802
Closes #904

cam6_3_134: Update atmospheric_physics external

---

bld/build-namelist
cime_config/config_pes.xml
src/dynamics/fv/dyn_grid.F90

This is needed for waccm(x) on derecho.  This fix was merged into cam_development at tag cam6_3_008.
fixes #901

part of cam_cesm_2_2_rel_09: corrrection for zonal mean history output

---

cime_config/config_compsets.xml
cime_config/config_pes.xml

Also adds a pelayout for <grid name="a%ne0np4CONUS" > on derecho.

part of cam_cesm2_2_rel_09: remove cism from all f compsets on CESM2_2 branch

---

Externals.cfg
bld/Makefile.in
cime_config/config_pes.xml
doc/ChangeLog_template
test/system/CAM_runcmnd.sh
test/system/archive_baseline.sh
test/system/test_driver.sh

Modifications to allow the cesm2_1 branch of CAM to run on derecho
closes #921 
Closes #923 
@adamrher wanted to monitor this PR

cam_cesm2_1_rel_60: Fix derecho tests on cesm2_1 branch

---

src/control/cam_history.F90

Fix for multiple monthly average history files.

---

bld/configure

on derecho.   Without this change using intel-oneapi or intel-classic will result in an error from cam configure:
`ERROR: Command: '/glade/work/jedwards/sandboxes/cesm2_x_alpha/components/cam/bld/configure -s -fc_type intel-oneapi -dyn se -hgrid ne30np4.pg3 -cpl nuopc -usr_src /glade/derecho/scratch/jedwards/SMS_Ln9.ne30pg3_ne30pg3_mg17.FHIST.derecho_intel-oneapi.20240308_140143_2n0bg8/SourceMods/src.cam -spmd -nosmp -ocn docn -phys cam6' failed with error 'ERROR: intel-oneapi is not a valid value for parameter fc_type: valid values are cray,pgi,intel,gnu,pathscale,ibm,nag,nvhpc,pgi-gpu,nvhpc-gpu' from dir '/glade/derecho/scratch/jedwards/SMS_Ln9.ne30pg3_ne30pg3_mg17.FHIST.derecho_intel-oneapi.20240308_140143_2n0bg8/Buildconf/camconf'
`

part of cam6_3_153: fix so that all three flavors of intel compiler are recognized 

---

cime_config/SystemTests/sct.py

This PR has been tested using the most recent CAM and includes the ChangeLog for #1019
Closes #1019

Fix for SCT when using ccs_config_ces0.0.99 on derecho

---

cime_config/SystemTests/sct.py

The mpibind script used on derecho was having trouble running a single process task in a pbs set up for a full node of tasks - the issue was that ESMF thought you were still using 128 tasks.   The workaround is to adjust the environment variable PBS_SELECT before starting the second job.  I have confirmed this works in test SCT_D_Ln7.T42_T42_mg17.QPC5.derecho_intel.cam-scm_prep using cam6_3_144 
Closes #1017

workaround so that sct works on derecho

---

src/control/cam_history.F90

Reorders variables in the rh files.  Significantly improves file write performance on derecho.  
Fixes #1042

improve performance of rh file write

---

.gitmodules
src/physics/rrtmgp/radiation.F90
src/physics/rrtmgp/rrtmgp_inputs.F90

Modify the RRTMGP interface for the special case when the minimum valid pressure for RRTMGP (1 Pa) falls in the top model layer (as it does in CAM's 93 level MT configuration).  The modification is to use the "extra layer" code path, and add a very thin extra layer just below 1 Pa.  The algorithm to calculate the midpoint pressure in the "extra layer" has changed from the original (which assumed a model top at 0 Pa).  Hence the change affects answers for the low top model configurations (LT and cam6) as well as the MT configuration.
Note that this modification is still being tested for scientific validity in the MT configuration.
Issue #1097 - HEMCO reference in .gitmodules is a branch not a tag.
- Modify .gitmodules to resolve #1097
Closes #1097 
Closes #1063

cam6_4_016: Modify RRTMGP interface for MT configurations.

---

.github/workflows/fleximod_test.yaml
.gitmodules
.lib/git-fleximod/git_fleximod/cli.py
.lib/git-fleximod/git_fleximod/git_fleximod.py
.lib/git-fleximod/git_fleximod/submodule.py
.lib/git-fleximod/pyproject.toml
.lib/git-fleximod/tbump.toml

Update to the latest version of git-fleximod and add the continuous integration git-fleximod test to the github workflows
A &ensp;&ensp;.github/workflows/fleximod_test.yaml: github workflow for git-fleximod CI tests
M &ensp;&ensp;.lib/git-fleximod/*: updates to latest version of git-fleximod (8.4)
M &ensp;&ensp; .gitmodules: fix DONOTUSE url for cice
closes #1113

cam6_4_018: Update git-fleximod to 8.4 and add fleximod_test workflow

---

bld/namelist_files/use_cases/waccm_sc_2000_cam6.xml
bld/namelist_files/use_cases/waccm_sc_2010_cam6.xml

Cycle over appropriate years in waccm forcings input datasets.
closes #1030

part of cam6_4_020:  Corrections to waccm forcings in FWsc2000climo and FWsc2010climo compsets

---

.github/scripts/branch_pr_issue_closer.py

This PR should allow the issue-closing script to work on the `cam_development` branch like it did previously.  
However, it also means that there is currently no multi-branch checking, so the script will need modification (or at least we all will need to be careful) once a new release branch has been created. 
Fixes #1119

Remove project checks from issue-closing script.

---

src/dynamics/mpas/driver/cam_mpas_subdriver.F90
src/dynamics/mpas/dyn_grid.F90

This PR addresses issues that were seen when using ncdata with longitudes in the $[-\pi, \pi]$ range in cases with full physics.  This would cause the atmosphere to become unphysical and runs to fail. This change is made just after the longitude values are read to ensure they are correct for the remainder of execution.
Fixes #1094

part of cam6_4_033: Wrap MPAS longitude values to [0,2pi) range

---

src/control/cam_snapshot_common.F90
src/physics/cam/check_energy.F90
src/physics/cam/physics_types.F90

Closes #1141 
Saves second dimension (dycore formula) of total energy and total water initial and current condition.
Companion PR in CAM-SIMA to read updated snapshot file and updates to standard names: 
https://github.com/ESCOMP/CAM-SIMA/pull/296

cam6_4_034: Add missing total energy in physics state from dycore in snapshots and cleanup total water

---

.gitmodules
cime_config/SystemTests/plb.py
cime_config/SystemTests/sct.py
cime_config/SystemTests/sub.py
cime_config/SystemTests/tmc.py
test/system/test_driver.sh

The externals have been updated as follows:
ccs_config_cesm1.0.0 -> ccs_config_cesm1.0.7
cime6.1.0            -> cime6.1.29
cmeps1.0.2           -> cmeps1.0.16
cdeps1.0.48          -> cdeps1.0.53
pio2_6_2             -> pio2_6_3
ctsm5.2.027          -> ctsm5.3.002
fi_240516            -> fi_240828
Issue #1134 - PLB,SCT,SUB, and TMC test need to be updated for cime6.1.12
. The fix in this issue needs to be applied to this commit since cime6.1.0 has been updated to cime6.1.29
Fixes #1134
Found during testing: need to modify `test_driver.sh` to not add the `--queue main` argument to the `create_test` command for derecho.  This is due to a change in how the derecho queues are set up.

cam6_4_039: update externals to cesm3_0_alpha03d

---

src/physics/rrtmgp/rrtmgp_inputs.F90

@jedwards4b reported: All of the coupled tests using the new cam tag seem to be blowing up with an error in radiation_tend: 
```
radiation_tend: ERROR: kdist_lw%gas_optics: gas_optics(): array tsfc has values outside range
```
This fix applies the same limiter to the `t_sfc` array passed to the gas optics as is already being applied to the atmosphere temperatures that are passed.

cam6_4_044: limit t_sfc to valid temperature range

---

bld/namelist_files/namelist_defaults_cam.xml
src/physics/cam/cam_snapshot.F90
src/physics/cam/clubb_intr.F90

The computation of the Exner function in the CLUBB interface code currently passes an incorrect version to the PBL utilities. The PBL utilities expect the "Stull" definition of the Exner function rather than the traditional "atmospheric" Exner function. Code provided by @adamrher 
closes #1222
The CLUBB group (@bstephens82) has recommended a namelist change to address this issue.
closes #1208

cam6_4_058: Fix Exner bug in CLUBB interface and change CLUBB namelist

---

bld/namelist_files/namelist_defaults_cam.xml

Closes #1251 
Closes #1249 
No need for this test anymore.   I checked out a CESM configuration and used this branch in it.  I then ran a create_newcase using the same compset/grid that Cecile is using and confirmed that I got all of the requested settings after running preview_namelists.  _[@cecilehannay - Could you please checkout this branch and make sure  that you get the namelist settings you want?  I tested it with an FLTHIST and it worked.}_  
@briandobbins - Does this PR indeed close your issue?
@ekluzek - Including you in case you see any problems

cam6_4_063: Update namelist settings

---

cime_config/testdefs/testmods_dirs/cam/outfrq9s_gpu_default/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_gpu_pcols760/shell_commands
src/physics/rrtmgp/radiation.F90

This PR fixes the broken RRTMGP GPU tests reported in #997 . The changes are borrowed from the EarthWorks code base (https://github.com/EarthWorksOrg/CAM/pull/25, thanks to John and Supreeth).
I used the `cam6_4_064` tag on Derecho and confirmed that running PUMAS+CLUBB+RRTMGP on the NVIDIA A100 GPU now passed the ensemble consistency test.
The CPU tests should be BFB. I updated the GPU tests to enable the RRTMGP GPU code so the results were different from the existing baseline as expected.

cam6_4_072: Fix broken RRTMGP GPU tests

---

src/physics/cam_dev/micro_pumas_cam.F90

Resolves #844.
This additional code in cam_dev/micro_pumas_cam.F90 will allow a run using cam_dev and SILHS, i.e. something like
~~~
CAM_CONFIG_OPTS="-phys cam_dev -silhs -psubcols 4"
~~~
to run without hitting the [pcols*psubcols abort error](https://github.com/ESCOMP/CAM/blob/776400d2a56d1c95551c9782810e4120ecb4f111/src/physics/cam/subcol.F90#L393) in subcol.F90.  This code is not super familiar to me, so my proposed fix (worked out with advice from @cacraigucar) may not be optimal yet, however I've tested it and it does work to get past the error and the model appears to be running normally afterward although I have not performed a months-long test yet.  
Furthermore, this will **not** resolve a separate problem which seems more general to any subcolumns, where subcolumns print as …

part of cam6_4_075: cam_dev silhs bug fix

---

src/dynamics/mpas/dp_coupling.F90

Purpose of changes (include the issue number and title text for each relevant GitHub issue):
- fix issue with mid-level pressure not being bounded by interface pressures in MPAS physics-dynamics coupling: https://github.com/ESCOMP/CAM/issues/1268
- fix Exner bug in MPAS physics-dynamics coupling: https://github.com/ESCOMP/CAM/issues/753
Not able to add @kuanchihwang as a reviewer ...
Please note we need to make this change in CAM-SIMA as well.
Closes #1268 
Closes #753

cam6_4_092: MPAS dp_coupling bug fixes

---

bld/namelist_files/namelist_definition.xml
cime_config/testdefs/testlist_cam.xml
cime_config/testdefs/testmods_dirs/cam/outfrq9s_ctem/shell_commands
cime_config/testdefs/testmods_dirs/cam/outfrq9s_ctem/user_nl_cam
cime_config/testdefs/testmods_dirs/cam/outfrq9s_ctem/user_nl_clm
src/control/runtime_opts.F90
src/physics/cam/physpkg.F90
src/physics/cam7/physpkg.F90
src/utils/ctem_diags_mod.F90
src/utils/esmf_check_error_mod.F90
src/utils/esmf_lonlat_grid_mod.F90
src/utils/esmf_phys2lonlat_mod.F90
src/utils/esmf_phys_mesh_mod.F90
src/utils/esmf_zonal_mean_mod.F90

Provides an method alternative to of computing zonal-mean terms of the Transformed Eulerian Mean (TEM) diagnostics.
The method here uses regridding capabilities provided in the ESMF library to map the dynamical fields needed in TEM diagnostics from the physics grid to a distributed regular longitude - latitude grid.  The TEM diagnostics are computed on this regular longitude - latitude grid and computing zonal means is straightforward.

cam6_4_097: An alternative for TEM diagnostics
