ESCOMP/CAM

Externals.cfg, cime_config/config_component.xml, cime_config/config_compsets.xml
ChangeLog will be modified before the commit
=> Update  AQP11 to AQPCONST and ww3 external to git

cime_config/config_component.xml, cime_config/config_compsets.xml
modified:   cime_config/config_component.xml
modified:   cime_config/config_compsets.xml
See issue #34
=> cam_cesm2_1_rel_38: Updates to compsets at 2-deg resolution

src/cpl/nuopc/atm_comp_nuopc.F90, src/cpl/nuopc/atm_import_export.F90, src/cpl/nuopc/atm_shr_methods.F90
These are just changes to the NUOPC cap.
=> nuopc changes to be consistent with head of CMEPS

bld/namelist_files/namelist_definition.xml, src/dynamics/fv/cd_core.F90, src/dynamics/fv/d2a3dikj.F90, src/dynamics/fv/dp_coupling.F90, src/dynamics/fv/dyn_comp.F90, src/dynamics/fv/dyn_grid.F90, src/dynamics/fv/dynamics_vars.F90, src/dynamics/fv/sw_core.F90, src/dynamics/fv/te_map.F90, src/dynamics/fv/uv3s_update.F90
=> cam_cesm2_1_rel_40: AM conservation updates

bld/perl5lib/Build/ChemPreprocess.pm
=> part of cam6_2_011: bug fix for including user chemmech file; update to latest git paths

bld/namelist_files/namelist_definition.xml, cime_config/testdefs/testmods_dirs/cam/waccmx_weimer/user_nl_cam, src/control/runtime_opts.F90, src/physics/cam/lunar_tides.F90, src/physics/cam/physpkg.F90, src/utils/time_manager.F90
new file:   src/physics/cam/lunar_tides.F90
modified:   bld/namelist_files/namelist_definition.xml
modified:   cime_config/testdefs/testmods_dirs/cam/waccmx_weimer/user_nl_cam
modified:   doc/ChangeLog
modified:   src/control/runtime_opts.F90
modified:   src/physics/cam/physpkg.F90
modified:   src/utils/time_manager.F90
closes #36 
New PR of #42
=> cam6_2_012: Add lunar tides forcings

src/cpl/nuopc/atm_comp_nuopc.F90
This PR bring in changes where orbital values for the nuopc cap are set in the cap since the driver is only an ascii file now.
=> cam6_2_016: updates of cam nuopc cap 

bld/namelist_files/use_cases/waccm_tsmlt_ssp534ext_cam6.xml, bld/namelist_files/use_cases/waccm_tsmlt_ssp585ext_cam6.xml, cime_config/config_component.xml, cime_config/config_compsets.xml
Replaces PR#105
Closes #102
Closes #98
=> cam_cesm2_1_rel_43: extended WACCM SSP compsets

bld/namelist_files/namelist_definition.xml, cime_config/testdefs/testlist_cam.xml, cime_config/testdefs/testmods_dirs/cam/outfrq9s_wetdep/shell_commands, cime_config/testdefs/testmods_dirs/cam/outfrq9s_wetdep/user_nl_cam, cime_config/testdefs/testmods_dirs/cam/outfrq9s_wetdep/user_nl_clm, src/chemistry/aerosol/wetdep.F90, src/chemistry/modal_aero/aero_model.F90, src/chemistry/modal_aero/modal_aero_convproc.F90, src/chemistry/modal_aero/modal_aero_data.F90, src/chemistry/mozart/mo_extfrc.F90, src/physics/cam/micro_mg_cam.F90, src/utils/time_manager.F90
These new features are turned off by default.  Baselines should be bit-for-bit unchanged.
closes issue #91
closes issue #92 -- bug fix for noleap calendar with ESMF lib
closes PR #99
=> cam6_2_021: Enhancements to wet removal of aerosols

bld/namelist_files/use_cases/ssp126_cam6.xml, bld/namelist_files/use_cases/ssp245_cam6.xml, bld/namelist_files/use_cases/ssp370_cam6.xml, bld/namelist_files/use_cases/ssp585_cam6.xml
Updates from Jim Edwards
Closes #117 
Already reviewed in #117
=> update SSP emissions files with anthropogenic forcing contributions

bld/namelist_files/use_cases/waccm_ma_2000_cam6.xml, bld/namelist_files/use_cases/waccm_tsmlt_2000_cam6.xml, cime_config/config_compsets.xml, cime_config/testdefs/testlist_cam.xml
Add WACCM middle atmosphere Add 2000climo compset for WACCM middle-atmosphere (FWma2000climo).
Updates for 2-degrees FW2000climo (WACCM TSML)
closes issue #123
=> cam6_2_023: Add FWma2000climo; updates to 2-deg FW2000climo

src/dynamics/se/interp_mod.F90
fixes #179: Bug in SE/CSLAM interpolated output.
=> cam6_2_040: bug fix for SE interpolated output

bld/namelist_files/use_cases/waccmx_ma_hist_cam6.xml
modified:   bld/namelist_files/use_cases/waccmx_ma_hist_cam6.xml
modified:   doc/ChangeLog
closes #191
=> cam6_2_044: provide IC files for FXHIST compset

cime_config/config_compsets.xml, src/dynamics/fv3/dyn_comp.F90, test/system/test_driver.sh
modified:   cime_config/config_compsets.xml
modified:   src/dynamics/fv3/dyn_comp.F90
closes #172 
closes #177 
fixes #206
=> cam_cesm2_2_rel_01: CAM-Chem CONUS ref cases; fv3 abort if non-hydrostatic

.github/scripts/branch_pr_issue_closer.py, .github/workflows/branch_push_workflow.yml
Adds the Github Action push workflow and issue closing script to the CESM2.1 release branch.  This should allow for issues to be closed automatically via keywords for any PRs that are associated with CESM2.1.
Fixes #209
=> Add Github Action push workflow to CESM2.1 release branch.

bld/build-namelist, cime_config/usermods_dirs/scam_SAS/user_nl_cam, cime_config/usermods_dirs/scam_arm95/user_nl_cam, cime_config/usermods_dirs/scam_arm97/user_nl_cam, cime_config/usermods_dirs/scam_atex/user_nl_cam, cime_config/usermods_dirs/scam_bomex/user_nl_cam, cime_config/usermods_dirs/scam_cgilsS11/user_nl_cam, cime_config/usermods_dirs/scam_cgilsS12/user_nl_cam, cime_config/usermods_dirs/scam_cgilsS6/user_nl_cam, cime_config/usermods_dirs/scam_dycomsRF01/user_nl_cam, cime_config/usermods_dirs/scam_dycomsRF02/user_nl_cam, cime_config/usermods_dirs/scam_gateIII/user_nl_cam, cime_config/usermods_dirs/scam_mpace/user_nl_cam, cime_config/usermods_dirs/scam_rico/user_nl_cam, cime_config/usermods_dirs/scam_sparticus/user_nl_cam, cime_config/usermods_dirs/scam_togaII/user_nl_cam, cime_config/usermods_dirs/scam_twp06/user_nl_cam, src/dynamics/se/dyn_comp.F90, test/system/test_driver.sh
- Fix test_driver root directory search
- Fix usermods for SCAM files
- Add csw_specifier to special list of filename-containing name list variables
- Add kill switch for se_molecular_diff > 0
fixes #213 
fixes #214 
fixes #206 
addreses #208
=> Bug fixes and kill switch for WACCM-SE issue

cime_config/config_compsets.xml
=> Remove FCSCAM compset

Externals.cfg, bld/namelist_files/namelist_definition.xml, doc/ChangeLog_template, src/control/scamMod.F90, src/dynamics/eul/iop.F90, src/physics/cam/physpkg.F90, src/physics/rrtmg/radiation.F90, src/physics/rrtmg/rrtmg_state.F90, test/system/CAM_compare.sh, test/system/TGIT.sh, test/system/test_driver.sh
Fix rrtmg_state pointer bug, correct SCAM6 namelist inconsistencies and update izumi compilers and TGIT test
Closes #86 
Closes #130 
Closes #145
Also updates TGIT regression test
=>  Misc bugs #1: rrtmg_state pointer, SCAM namelist, izumi compiler and TGIT test

bld/build-namelist, cime_config/config_pes.xml, doc/ChangeLog_template, src/chemistry/modal_aero/modal_aero_rename.F90, src/physics/cam/physpkg.F90
Misc bug fixes 2 for CESM2_1 branch
Closes #131 
Closes #214 
Closes #185 
Closes #126
=> cam_cesm2_1_rel_47: Fix modal_aero_rename opens too many files, FCHIST test failure, CAM_diagnostics memory leak, update config_pes.xml

.github/scripts/branch_pr_issue_closer.py
This is the same as PR #243 , except it is for the `cam_cesm2_2_rel` branch.
=> Fix bug in issue-closing script for CESM2.2 branch

.github/scripts/branch_pr_issue_closer.py
This is the same as PR #243 , except it is for the `cam_cesm2_1_rel` branch.
Fixes #242
=> Fix bug in issue-closing script for CESM2.1 branch

bld/namelist_files/use_cases/histBB_cam6.xml, cime_config/config_component.xml
Fixes #249 
Note that testing of these changes will be done in cime.   These changes are only for the CESM2.1 branch.
=> CESM2-LE smoothed BB forcing

Externals.cfg
=> cam6_3_003: update to cime5.8.32

bld/namelist_files/use_cases/ssp370BB_cam6.xml, cime_config/config_component.xml
Add a use_case for ssp370BB.
Fixes #266
=> cam_cesm2_1_rel_50: Updates needed for ssp370BB

src/utils/cam_grid_support.F90
=> Removed _FillValue from CAM grid data on output files

bld/namelist_files/use_cases/ssp245BB_cam6.xml, cime_config/config_component.xml
Add a use_case for ssp245BB forcing.  No regression testing were carried out since those test wouldn't test this change.
Therefore, no baselines where created.
Fixes #293
=> cam_cesm2_1_rel_53: Updates needed for ssp245BB

Externals.cfg, src/control/cam_history.F90, src/control/cam_history_support.F90, src/control/sat_hist.F90, src/physics/cam/physics_buffer.F90.in, src/physics/cam/subcol_pack_mod.F90.in, src/physics/cam/subcol_tstcp.F90, src/utils/cam_grid_support.F90, src/utils/cam_pio_utils.F90
Closes #307
Don't expect that I will need to make further changes, but won't know until testing completes.  Right now izumi is failing a number of tests, but that is not unexpected due to unreliability of current testing on izumi.
=> cam6_3_009?: Update externals to match cesm2_3_alpha02a

src/cpl/mct/atm_comp_mct.F90, src/cpl/nuopc/atm_comp_nuopc.F90, src/physics/cam/micro_mg_cam.F90, src/physics/cam_dev/physpkg.F90, src/physics/camrt/radiation.F90, src/physics/rrtmg/radiation.F90, src/physics/simple/radiation.F90
Fixes https://github.com/ESCOMP/CAM/issues/491
=> part of cam6_3_041: mods to pass cam_dev ERP tests, misc cam_dev bug fixes

Externals.cfg, cime_config/testdefs/testmods_dirs/cam/idphys/shell_commands, cime_config/testdefs/testmods_dirs/cam/outfrq24h_port/shell_commands, cime_config/testdefs/testmods_dirs/cam/outfrq3s_eoyttrac/shell_commands, cime_config/testdefs/testmods_dirs/cam/outfrq3s_ttrac/shell_commands, cime_config/testdefs/testmods_dirs/cam/scm_prep/shell_commands, cime_config/testdefs/testmods_dirs/cam/scm_prep_c6/shell_commands, cime_config/testdefs/testmods_dirs/cam/silhs/shell_commands, cime_config/testdefs/testmods_dirs/cam/terminator/shell_commands, cime_config/testdefs/testmods_dirs/cam/ttrac_loadbal0/shell_commands, cime_config/testdefs/testmods_dirs/cam/ttrac_loadbal1/shell_commands, cime_config/testdefs/testmods_dirs/cam/ttrac_loadbal3/shell_commands
Closes #548 
Closes #553 (This bug was discovered during testing)
=> cam6_3_054: Update externals to match cesm2_3_beta08

Externals.cfg, src/cpl/nuopc/atm_comp_nuopc.F90, src/cpl/nuopc/atm_import_export.F90
This PR updates the Externals.cfg file and also incorporates fixes for the SCT_D_Ln7_Vnuopc.T42_T42_mg17.QPC5.cheyenne_intel.cam-scm_prep to pass.
=> part of cam6_3_056: fixes for SCT tests to pass

cime_config/testdefs/testlist_cam.xml, src/control/cam_snapshot_common.F90, src/dynamics/se/dycore/global_norms_mod.F90, src/physics/cam/gw_common.F90, src/physics/cam/gw_drag.F90, src/physics/cam/gw_rdg.F90, src/physics/cam/ssatcontrail.F90
Issues being closed:
Closes #362 (contrail bug fix)
Closes #610  (SE dycore writes)
Closes #606 (cam_snapshot fix)
PRs being closed:
Closes #535 (contrail bug fix)
Closes #447 (GW diags)
Note to reviewers:  #535 and #447 were already reviewed.  The only unreviewed files are:  cam_snapshot_common.F90 and global_norms_mod.F90.  Also note that most of the changes in these two files are whitespace.  The actual code changes are minimal
=> cam6_3_065:  Misc tag for Gravity Wave, contrail, cam_snapshot and SE dycore writes

Externals.cfg, cime_config/testdefs/testlist_cam.xml
=> cam6_3_068: Update externals to match cesm2_3_alpha09c

Externals.cfg
=> Update CTSM external to csm5.1.dev102

Externals.cfg
=> cam6_3_070: Update CTSM tag to dev103 - bug fix tag

src/dynamics/se/dycore/fvm_mapping.F90, src/dynamics/se/dycore/prim_advance_mod.F90, src/utils/physconst.F90
These changes were made by @PeterHjortLauritzen 
Closes #633 
Closes #551 
Closes #392 (one modification from this issue was brought in here)
=> cam_cesm2_2_rel_04: 3 bug fixes for CESM2.2 release

Externals_CAM.cfg
Closes #641 
Also brings in a few GPU code updates. Does not change answers.
=> Point to new PUMAS Externals tag

.github/workflows/branch_push_workflow.yml
Fixes #718
Also updates the Github checkout versions in order to avoid deprecation problems.
=> Update issue closing workflow in CESM2.2 release branch

src/cpl/nuopc/atm_comp_nuopc.F90
Fixes issue #720 updates from deprecated shr_file_mod to shr_log_mod.
=> part of cam6_3_087: mv shr_file to shr_log, fix issue in logunit

src/chemistry/mozart/chemistry.F90
=> cam6_3_096:  aqueous chemistry fix

Externals_CAM.cfg, bld/build-namelist, bld/namelist_files/namelist_defaults_cam.xml, bld/namelist_files/namelist_definition.xml, src/physics/cam/hetfrz_classnuc.F90, src/physics/cam/hetfrz_classnuc_cam.F90, src/physics/cam/microp_aero.F90
Apply 0.05 scaling factor to the dust contribution to het freezing.
Use more physical approach to derive dust and BC number densities.
=> cam6_3_097: Updates to heterogeneous freezing code

src/physics/cam/cospsimulator_intr.F90, src/physics/cam_dev/convect_diagnostics.F90, src/physics/cam_dev/physpkg.F90
=> Add pbufs for camdev and cosp

src/chemistry/mozart/chemistry.F90
=> Initialize CO2 when not available in initial conditions file

manage_externals/.github/workflows/bumpversion.yml, manage_externals/.github/workflows/tests.yml, manage_externals/.gitignore, manage_externals/.travis.yml, manage_externals/README.md, manage_externals/checkout_externals, manage_externals/manic/checkout.py, manage_externals/manic/externals_description.py, manage_externals/manic/externals_status.py, manage_externals/manic/repository_factory.py, manage_externals/manic/repository_git.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py, manage_externals/manic/utils.py, manage_externals/test/README.md, manage_externals/test/repos/README.md, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_sys_repository_git.py, manage_externals/test/test_unit_externals_description.py, manage_externals/test/test_unit_externals_status.py, manage_externals/test/test_unit_repository.py, manage_externals/test/test_unit_repository_git.py, manage_externals/test/test_unit_repository_svn.py, manage_externals/test/test_unit_utils.py
Update manage_externals to [manic-1.2.22](https://github.com/ESMCI/manage_externals/releases/tag/manic-1.2.22)
Closes #740 
Initial checkouts were tested on cheyenne and izumi and they worked
=> cam6_3_113: Update manage_externals

bld/build-namelist, bld/namelist_files/namelist_defaults_cam.xml, bld/namelist_files/use_cases/2000_cam6.xml, bld/namelist_files/use_cases/2010_cam6.xml, bld/namelist_files/use_cases/waccm_sc_2000_cam6.xml, bld/namelist_files/use_cases/waccm_sc_2010_cam6.xml
Adjustments to the SOAE emissions factors and correction to default 10x15 CAMChem IC file.
closes #860 
closes #867
=> cam6_3_121: Corrections to namelist settings

Externals.cfg
Closes #905 
Answer changes are due to answer changing CMEPS tag:  https://github.com/ESCOMP/CMEPS/pull/394
=> cam6_3_131: Update externals to get job_priority setting on derecho

cime_config/testdefs/testlist_cam.xml, test/system/archive_baseline.sh, test/system/test_driver.sh
=> part of cam6_3_145: Remove cheyenne testing and make all cheyenne tests be derecho ones

Externals.cfg, cime_config/testdefs/testlist_cam.xml
Closes #985 
Closes #1021 
Closes #1025
=> Update to alpha17 externals

test/system/archive_baseline.sh
Add the compiler name to derecho baseline directories
Closes #1125
=> Add compiler name to derecho baseline directories

.gitmodules
Update CTSM to ctsm5.2.027
The following are expected to affect CAM F compsets in a substantial way:
- ctsm5.2.016 -- changes answers for clm6_0 for crop grid cells
- ctsm5.2.020 -- changes answers for all physics options for MEGAN BGVOC's which will affect CAM-Chem simulations
- ctsm5.2.026 -- change answers for clm6_0 over urban grid cells
Closes #1139
=> cam6_4_027: update ctsm tag to ctsm5.2.027

src/dynamics/mpas/driver/cam_mpas_subdriver.F90
=> needed to update share beyond share1.1.7

cime_config/config_archive.xml
Adds timestamp to rpointer files in config_archive.xml
Fixes #1293 this fix also requires https://github.com/ESMCI/cime/pull/4786
=> update to handle timestamped rpointer files

.gitmodules, src/physics/rrtmgp/radiation.F90
This PR fixes the memory leaks discovered by the EarthWorks team. Mostly nvhpc-specific. Fixes include:
- coords_1d bugfix - https://github.com/ESCOMP/atmospheric_physics/pull/254
- RRTMPG bugfix - https://github.com/ESCOMP/atmospheric_physics/pull/255
closes #1318
=> cam6_4_100: Memory leak fixes
